export const reducerCases = {
  SET_TOKEN: "SET_TOKEN",
  SET_PLAYLISTS: "SET_PLAYLISTS",
  SET_USER: "SET_USER",
  SET_PLAYLIST: "SET_PLAYLIST",
  SET_SELECTED_PLAYLIST_ID: "SET_SELECTED_PLAYLIST_ID",
  SET_CURRENTLY_PLAYING: "SET_CURRENTLY_PLAYING",
};
